### ISSUE TITLE
Ablation Study Question

### ISSUE THREAD

**Issue by dihuangcode** [wei-mao-2019/LearnTrajDep#1]
Hi, @wei-mao-2019 

Thanks for your awesome work !!

I read your paper , noticed that you did ablation study that removed dct component from whole pipeline. So how did you handle temporal dimension without dct? Did you mean feed (K, L * T) to linear1024 network? 

: )

**Comment by wei-mao-2019** [comment]
Hi @dihuangcode 

If you mean the ablation study in table 6 in our paper,  a K * L matrix will be fed to the GCN. K is the number of joint coordinates / angles. L is the sequence length. If it is with DCT, then each row of the input matrix is the DCT coefficients of one coordinate / angle. Otherwise, each row is simply the sequence of one coordinate / angle values (without DCT).

Cheers

**Comment by dihuangcode** [comment]
yeah, but I thought it should be like (3, K, L), if you use joint coordinates, since there are three directions. I just curious about you handle this '3'.

Thanks @wei-mao-2019

**Comment by dihuangcode** [comment]
oh.. I ran your code and understood your methods. In fact your graph node has already encode the feature dimension. So.. Does that mean your graph has nothing to do with human structure ?

**Comment by wei-mao-2019** [comment]
Hi @dihuangcode ,

It does not only capture the human kinematic like hands are only connected to elbows. It can capture the long range dependencies on the kinematic tree as we explained in our paper.

Thank you
Cheers

**Comment by dihuangcode** [comment]
Thanks for your quick reply~ @wei-mao-2019 

Human structure of H3.6M has 16 joints, right? But your graph contains 48 nodes. So I think maybe it's not proper to explain the graph using human structure.

**Comment by tracer9** [comment]
@dihuangcode 
Hi, I also focus on this project. In my opinion, when the dataloader selects the "dim_used" dimension, the human structure has already destroied. 

“D = K x 3” didn't hold anymore, where D means dimension, K means number of joints.

What's your opinion?

**Comment by tracer9** [comment]
@dihuangcode 

https://github.com/wei-mao-2019/LearnTrajDep/blob/master/utils/data_utils.py#L675

maybe this line would help.

**Comment by wei-mao-2019** [comment]
Hi, @dihuangcode.  It is human structure, if all 3 coordinates or angles of one joint are connected with the other joint according to the human kinematic tree. Our structure is more than human structure since it is fully connected. 

If you look into the dataset you will find that some joints do not have 3 degree of freedom in terms of rotation angle e.g. elbows and are fixed in terms of 3d coordinate, it not necessary to predict them, they are constant. That is why we have 48 nodes in our experiments.

Cheers

**Comment by dihuangcode** [comment]
Great !!!  @wei-mao-2019 

It really makes sense, thank you for your reply!

**Comment by dihuangcode** [comment]
> @dihuangcode
> Hi, I also focus on this project. In my opinion, when the dataloader selects the "dim_used" dimension, the human structure has already destroied.
> 
> “D = K x 3” didn't hold anymore, where D means dimension, K means number of joints.
> 
> What's your opinion?

: )

wei mao has explained it clearly. I will close this issue. Anyone who has questions can continue this issue.
