### ISSUE TITLE
Forecasting long sequences

### ISSUE THREAD

**Issue by jutanke** [wei-mao-2019/LearnTrajDep#6]
What would be an appropriate method to forecast longer time sequences, e.g. 4 seconds? Should the model be retrained on a 4 seconds horizon or would an auto-regressive approach (using the output of one time step as the input for the next time step) suffice?

**Comment by wei-mao-2019** [comment]
Hi @jutanke,

I think, to generate very long sequence, it would be better to use a strong regularizer such as an discriminator. Since as the sequence become longer and longer, the relation between observed sequence and poses far in the future will be weaker and weaker, it is not reliable to only condition on observed sequence. 

I did not try AR before. It may work for very long sequence.

Cheers
Wei
