### ISSUE TITLE
#training frames

### ISSUE THREAD

**Issue by Yutasq** [wei-mao-2019/LearnTrajDep#9]
Hi @wei-mao-2019, nice work and thanks for sharing the code!
My question is that when you comparing the performance with Residual sup., convSeq2Seq, and AGED, why use 10 frames (400ms) as seed poses instead of 50 frames (2s) as trained in the above mentioned methods? Will it be more convincing if we compare all the methods with observing 10 frames and predict next 10/25 frames for short/long-term prediction?

Thank you.

**Comment by wei-mao-2019** [comment]
Hi @Yutasq,

Thank you for your interests.

We use 10 frames, because we found past 10 frames already contain enough information in terms of DCT coefficients for prediction.

Yes, it is worth trying to use 10 frames in other methods as well. My thinking is that for RNN based method it may not differ too much because even observed past 50 frames, the RNNs tends to focus more on recent inputs and ignore inputs that are far away.

Cheers
Wei

**Comment by Yutasq** [comment]
Hi @wei-mao-2019 , thanks for the response! This may also show that your method has potentials in achieving better prediction with less conditional information.

Thank you,
Yutas
